# NUMPY ARRAY

In [1]:
import numpy as np
a = np.array([10, 20, 30])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[10 20 30]


In [2]:
print(a.shape)       # ----> always return the tuple
print(a.ndim)
print(a.size)

(3,)
1
3


In [3]:
# multi diamentional array
b=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [4]:
print(b.shape)
print(b.ndim)
print(b.size)

(3, 3)
2
9


In [5]:
# range vs arange

l = [i for i in range(10)]    # -----> list
n = np.arange(10)             # -----> numpy array   

print(l)
print(n)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr = np.arange(0,20,2)
arr1 = np.arange(1,20)
arr2 = np.arange(20)

print(arr)
print(arr1)
print(arr2)

[ 0  2  4  6  8 10 12 14 16 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
# ndarry = n-diamentional array
type(a)

numpy.ndarray

In [8]:
import numpy as np
import time
import sys

# list --> size and time
list1=range(1000000)
list2=range(1000000)
            
t1=time.time()
S = [(a * b) for a,b in zip(list1,list2)]
t2=time.time()
print(f"size of each elements in list S :- {sys.getsizeof(S)}")
print(f"size of given list S :- {sys.getsizeof(S)*len(S)}")
lt=t2-t1
print(f"run time(list) :- {lt} second")
print(type(S))

print("   ")

# numpy array --> size and time
array1 = np.arange(1000000)
array2 = np.arange(1000000)

t3=time.time()
D = array1*array2
t4=time.time()
print(f"size of each elements in numpy array D :-{D.itemsize}")
print(f"size of given array D:-{D.itemsize*D.size}")
nt=t4-t3
print(f"run time(np array) :-{nt} second")
print(type(D))
# item data type
print(D.dtype)

size of each elements in list S :- 8697456
size of given list S :- 8697456000000
run time(list) :- 0.10952115058898926 second
<class 'list'>
   
size of each elements in numpy array D :-4
size of given array D:-4000000
run time(np array) :-0.0 second
<class 'numpy.ndarray'>
int32


In [9]:
#  arithmatic operation affect list vs array

l = [1,2,3,4,5]
arr = np.array([1,2,3,4,5])

print(f" original list :-- {l} ")
print(f" original array :-- {arr} ")

print("   ")

try:
    l = l+5
    print(f"modified list: {l}")
except:
    print("list does not support list+int")
    
print("   ")
    
try:
    arr = arr+5
    print(f"modified arr: {arr}")
except:
    print("np array does not support arr+int")

 original list :-- [1, 2, 3, 4, 5] 
 original array :-- [1 2 3 4 5] 
   
list does not support list+int
   
modified arr: [ 6  7  8  9 10]


In [10]:
# Array Mathematical operations 

import numpy as np

x = np.array([[1,2],[3,4]])

y = np.array([[5,6],[7,8]])

print(x)

print(y)

print(x + y) # or print(np.add(x, y)) 

print(x - y) # or print(np.sub(x, y))

print(x * y) # or print(np.mul(x, y))

print(x / y) # or print(np.div(x, y))

print(np.sqrt(x))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [11]:
# np array is mutable of not ?

a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a)

# Accessing Array elements of single dimentional array
print(a[0], a[1], a[2]) 

# Change an element of array
try: 
    a[0] = 50
    a[1] = 10
    print(f"updated array :- {a} and we proved that array is mutable..." )
except:
    print("np array is immutable")

[1 2 3 4 5 6 7 8]
1 2 3
updated array :- [50 10  3  4  5  6  7  8] and we proved that array is mutable...


In [12]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(a)

# Accessing Array elements of single dimentional array
print(a[0][0], a[0][1], a[1][2]) # or print(a[0,0], a[0,1], a[1,2])

# Change an element of array 
try: 
    a[0][0] = 50
    a[1][0] = 10
    print(f"updated array :- {a} ")
    print("and we proved that array is mutable...")
except:
    print("np array is immutable")

[[1 2 3 4]
 [5 6 7 8]]
1 2 7
updated array :- [[50  2  3  4]
 [10  6  7  8]] 
and we proved that array is mutable...


In [13]:
#  reshape
a = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])

print(a)
print("   ")

# shape
print(a.shape)
print("   ")

# reshape
print(a.reshape(4,2))

[[10 20 30 40]
 [50 60 70 80]]
   
(2, 4)
   
[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [14]:
# Array Indexing 

# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print("   ")

#Slicing in array
print(a.shape)
print("   ")

b = a[0:,2]      # 0: --> 1st, 2nd raw and 2 --> 2nd column ,... so we get [3 7 11]  
c = a[1:, 2:]    # 1: --> 1st, 2nd raw and 2: --> 2nd column  
d = a[0:2, 2:3]  

print(b)
print("   ")

print(c)
print("   ")

print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
   
(3, 4)
   
[ 3  7 11]
   
[[ 7  8]
 [11 12]]
   
[[3]
 [7]]


In [15]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1,:]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1)
print(row_r1.shape)  

print(row_r2)
print(row_r2.shape)

[5 6 7 8]
(4,)
[[5 6 7 8]]
(1, 4)


In [16]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# We can make the same distinction when accessing columns of an array:

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1)
print(col_r1.shape)  

print(col_r2)
print(col_r2.shape)  

[ 2  6 10]
(3,)
[[ 2]
 [ 6]
 [10]]
(3, 1)


In [17]:
#array indexing in form of integer 

a = np.array([[1,2], [3, 4], [5, 6]])

print(a[[0, 1, 2], [0, 1, 0]])    # or print(np.array(a[[0, 1, 2], [0, 1, 0]]))

print(a[0, 0], a[1, 1], a[2, 0])    # ----->> solve this ... |
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) 

[1 4 5]
1 4 5
[1 4 5]


In [18]:
print(np.linspace(1,4,10))     # generating 10 number in the interval of 1 to 4 (equally spaced)

[1.         1.33333333 1.66666667 2.         2.33333333 2.66666667
 3.         3.33333333 3.66666667 4.        ]


In [19]:
print(a.min())
print(a.max())
print(a.sum())

1
6
21


In [20]:
# axis (1=x and 0=y)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a.sum(axis=0))
print(a.sum(axis=1))

print("   ")

print(a.T)  # or print(a.transpose())   # transpose 

print("   ")

print(a.ravel())   #convert 2d array to 1d array

[15 18 21 24]
[10 26 42]
   
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
   
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
print(np.sqrt(a))

print(    )

print(np.std(a))    # Standard Deviation (SD) is measured as the spread of data distribution in the given data set.

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]

3.452052529534663


In [22]:
print(np.zeros((3,4)))
print(    )
print(np.ones((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
a = np.array([[1,2,3], [5,6,7], [9,10,11]])
print(np.linalg.inv(a))     # inverse of array (coumpulsary square array)

[[-1.93011413e+15  3.86022825e+15 -1.93011413e+15]
 [ 3.86022825e+15 -7.72045650e+15  3.86022825e+15]
 [-1.93011413e+15  3.86022825e+15 -1.93011413e+15]]


In [24]:
#  -----------------------------------------------------------------------------------------------------------------------  #