# 0.Import library

In [1]:
import numpy as np
import pandas as pd

# 1. Datatypes
pandas has two main datatypes, Series and DataFrame.

Series --->> a 1-dimensional column of data.                     
DataFrame (most common) - a 2-dimesional table of data with rows and columns.

# Pandas series

In [3]:
# - Series  (1d homogeneous array)
a = np.array([1,2,3,4])
print(a)

s = pd.Series(a)
print(s)

[1 2 3 4]
0    1
1    2
2    3
3    4
dtype: int32


In [4]:
a = np.array(['K','E','Y','U','R'])
print(a)

s = pd.Series(a)                      # here 0 1 2... is a index
print(s)

print(type(s))

['K' 'E' 'Y' 'U' 'R']
0    K
1    E
2    Y
3    U
4    R
dtype: object
<class 'pandas.core.series.Series'>


In [5]:
# Creating Pandas series with index:

import pandas as pd

import numpy as np

s1 = pd.Series( np.random.random(5) , index=['a', 'b', 'c', 'd', 'e'] )     # here a b c...is my one index

print(s1)

a    0.721826
b    0.589585
c    0.835393
d    0.057281
e    0.049895
dtype: float64


In [9]:
# Create a Series from dictionary

data = {'pi': 3.1415, 'e': 2.71828}  # dictionary

print(data)

s3 = pd.Series ( data )

print(s3)

{'pi': 3.1415, 'e': 2.71828}
pi    3.14150
e     2.71828
dtype: float64


In [6]:
a = np.random.randint(1,100,5)
print(a)

print(    )

b = np.random.randint(4,size=(4,5))
print(b)

[84 34 70 11 77]

[[0 1 0 0 1]
 [2 1 3 1 3]
 [1 2 3 1 1]
 [3 1 0 1 1]]


In [7]:
s = pd.Series(a)
print(s)

0    84
1    34
2    70
3    11
4    77
dtype: int32


In [27]:
import pandas as pd

import numpy as np

s1 = pd.Series( np.random.random(5) )

print(s1)

# Many ways to "slice" Pandas series (series have zero-based index by default):

print(s1[3])  # returns 4th element
print (    )

print(s1[:2]) #First 2 elements
print (    )

print(s1[1:]) #all element after 1st element
print (    )

print( s1[ [2,1,0]])
print (    )

print( s1[ [2,1,2]])
print (    )
# View index values


0    0.650222
1    0.428461
2    0.757881
3    0.798886
4    0.703698
dtype: float64
0.7988864921614459

0    0.650222
1    0.428461
dtype: float64

1    0.428461
2    0.757881
3    0.798886
4    0.703698
dtype: float64

2    0.757881
1    0.428461
0    0.650222
dtype: float64

2    0.757881
1    0.428461
2    0.757881
dtype: float64



In [38]:
print(s1.index)
print (    )

print(s1.max())
print (    )

print(s1.min())
print (    )

print(s1.sum())
print (    )

print(s1>0.5)
print (    )

print(s1[s1>0.5])
print (    )

print(s1.median())
print (    )

print(s1[s1>s1.median()])

RangeIndex(start=0, stop=5, step=1)

0.7988864921614459

0.42846053726423927

3.33914761950273

0     True
1    False
2     True
3     True
4     True
dtype: bool

0    0.650222
2    0.757881
3    0.798886
4    0.703698
dtype: float64

0.7036983186564415

2    0.757881
3    0.798886
dtype: float64


In [40]:
# Convert pd series into np array

s1.values

array([0.65022164, 0.42846054, 0.75788063, 0.79888649, 0.70369832])

In [42]:
# Unlike ndarray Series automatically allign the data based on label:

import pandas as pd

s5 = pd.Series (range(6))

print(s5)

print(s5[:-1])     #pritn escape last element

print(s5[::-1])

print(s5[1:])      # print after 1st index

s5[1:] + s5[:-1]

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64
0    0
1    1
2    2
3    3
4    4
dtype: int64
5    5
4    4
3    3
2    2
1    1
0    0
dtype: int64
1    1
2    2
3    3
4    4
5    5
dtype: int64


0    NaN
1    2.0
2    4.0
3    6.0
4    8.0
5    NaN
dtype: float64

In [43]:
mys = pd.Series( np.random.randn(5))

print(mys)

print(mys.empty)

print(mys.head(2))

print(mys.tail(2))

print(mys.values)

print(mys.dtype)    # or print(type(mys))

# ----------------pandas series finish-------------------

0    0.243507
1    0.361167
2   -2.041766
3   -1.098873
4   -1.200935
dtype: float64
False
0    0.243507
1    0.361167
dtype: float64
3   -1.098873
4   -1.200935
dtype: float64
[ 0.24350718  0.36116724 -2.04176573 -1.09887328 -1.2009346 ]
float64


# pandas dataframe

In [44]:
# - DataFrame (2d labeled heterogeneous array)
import pandas as pd

df =  pd.DataFrame({ 'Name': pd.Series(['Alice','Bob','Chris']), 

                  'Age': pd.Series([ 21,25,23]) } )

print(df)

#Add a new column:

df['height'] = pd.Series([5.2,6.0,5.6])

print(df)

    Name  Age
0  Alice   21
1    Bob   25
2  Chris   23
    Name  Age  height
0  Alice   21     5.2
1    Bob   25     6.0
2  Chris   23     5.6


In [9]:
df = pd.read_csv('datasets/Salaries.csv')

#Display a few first records

print(df.head(2))  # head() by default display top 5 values
print(    )

#List the types of all columns
print(df.dtypes)
print(    )

# List the column names
print(df.columns)
print(    )

#List the row labels and the column names
print(df.axes)
print(    )

#Number of dimensions
print(df.ndim)
print(    )

#Total number of elements in the Data Frame
print(df.size)
print(    )

#Number of rows and columns
print(df.shape)
print(    )

#Output basic statistics for the numeric columns
print(df.describe())
print(    )

#only print 1 column
print(df['salary'])
print(    )

#Calculate average of the columns
# <your code goes here>
print(df.mean())
print(     )

#Calculate average of the only one columns
# <your code goes here>
print(df['salary'].mean())
print(     )

#Calculate average of the columns in the first 50 rows
# <your code goes here>
print(df.head(50).mean())
print(     )

print(type(df))

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

[RangeIndex(start=0, stop=78, step=1), Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')]

2

468

(78, 6)

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

0     186960
1      93000
2     110515
3     131205
4     104800
       ...  
73    105450
74    104542
75  

In [19]:
df.describe()

phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64 
 3   service     78 non-null     int64 
 4   sex         78 non-null     object
 5   salary      78 non-null     int64 
dtypes: int64(3), object(3)
memory usage: 3.8+ KB


In [23]:
df.index

RangeIndex(start=0, stop=78, step=1)

In [24]:
df.head()

rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [25]:
df.tail()

rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [30]:
df.isnull().sum()

rank          0
discipline    0
phd           0
service       0
sex           0
salary        0
dtype: int64

In [31]:
df["phd"] = df["phd"].fillna(df["phd"].mean(),inplace=True)

In [32]:
df.dropna()

Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []

In [33]:
# Data Slicing and Grouping 
# ----> Groupby method follow the process of splitting data , applying a function and combining the required data.

#Group data using rank

df_rank = df.groupby('rank') # Do not display values  without operations 
print(df_rank)
print(df_rank.mean())

             service         salary
rank                               
AssocProf  11.307692   91786.230769
AsstProf    2.210526   81362.789474
Prof       21.413043  123624.804348


In [11]:
# If we use double brackets Pandas will produce a DataFrame
print(df.groupby('sex').mean())
print(    )

print(df.groupby('sex')[['salary']].mean())    #only one column

#Note- if single bracket used on salary it will display pandas series 

              phd    service         salary
sex                                        
Female  16.512821  11.564103  101002.410256
Male    22.897436  18.538462  115045.153846

               salary
sex                  
Female  101002.410256
Male    115045.153846


In [12]:
#Calculate mean salary for each professor rank:
print(df.groupby(['rank'])[['salary']].mean())
print(    )

print(df.groupby(['rank'], sort=False)[['salary']].mean())

                  salary
rank                    
AssocProf   91786.230769
AsstProf    81362.789474
Prof       123624.804348

                  salary
rank                    
Prof       123624.804348
AssocProf   91786.230769
AsstProf    81362.789474


In [13]:
# Filtering

#Select observation with the value in the salary column > 120K

df_sub = df[ df['salary'] > 160000]

print(df_sub)

print(   )

# Using filtering, find the mean value of the salary for the discipline A
print(df[df['discipline'] == 'A'].mean())
print(    )

print(df[df['discipline'] == 'A']['salary'].mean())

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
13  Prof          B   35       33    Male  162200
72  Prof          B   24       15  Female  161101

phd           21.527778
service       15.722222
salary     98331.111111
dtype: float64

98331.11111111111


In [14]:
"""
Extract (filter) only observations with high salary ( > 100K) 

and find how many female and male professors in each group

"""

df[df['salary'] > 100000].groupby('sex')[['salary']].count()

salary
sex           
Female      21
Male        25

In [34]:
# More on slicing the dataset
# When selecting one column, it is possible to use single set of brackets, but the resulting object will be  a Series (not a DataFrame)

#Select column salary:
print(df['salary'])

# When we need to select more than one column and/or make the output to be a DataFrame, we should use double brackets
#Select column salary:
print(df[['rank','salary']])

0     186960
1      93000
2     110515
3     131205
4     104800
       ...  
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64
         rank  salary
0        Prof  186960
1        Prof   93000
2        Prof  110515
3        Prof  131205
4        Prof  104800
..        ...     ...
73       Prof  105450
74  AssocProf  104542
75       Prof  124312
76       Prof  109954
77       Prof  109646

[78 rows x 2 columns]


In [38]:
# If we need to select a range of rows, we can specify the range using ":" 
#Select rows by their position:
print(df[10:20])

# """
# Method iloc (summary)

# df.iloc[0]                           # First row of a data frame

# df.iloc[i]                             #(i+1)th row

# df.iloc[-1]                          # Last row 

# df.iloc[:, 0]                        # First column

# df.iloc[:, -1]                       # Last column 

# df.iloc[0:7]                        #First 7 rows

# df.iloc[:, 0:2]                     #First 2 columns

# df.iloc[1:3, 0:2]                 #Second through third rows and first 2 columns

# df.iloc[[0,5], [1,3]]             #1st and 6th rows and 2nd and 4th columns
# """

        rank discipline   phd  service   sex  salary
10      Prof          B  None       33  Male  128250
11      Prof          B  None       23  Male  134778
12  AsstProf          B  None        0  Male   88000
13      Prof          B  None       33  Male  162200
14      Prof          B  None       19  Male  153750
15      Prof          B  None        3  Male  150480
16  AsstProf          B  None        3  Male   75044
17  AsstProf          B  None        0  Male   92000
18      Prof          A  None        7  Male  107300
19      Prof          A  None       27  Male  150500


In [ ]:
# -------------------------------------------------------------------------------------------------------------------------- #